settings:
  title: 'Status Page'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: 311281639e86c726 # unique identifier
    name: 311281639e86c726
    description: 'You write code. They handle the rest.' # default=empty
    url: 'https://311281639e86c726.xinnew.top/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: 零信任安全网关
    name: 希灵Security门户网站
    url: 'https://a2.shanshi.asia:30066/'
    method: GET
    expectStatus: 200

  - id: 零信任安全网关
    name: 零信任安全网关
    url: 'https://a2.shanshi.asia:30304/?src=connect'
    method: GET
    expectStatus: 200
    
  - id: 2c53ce48eb97cb20
    name: 2c53ce48eb97cb20
    description: 'Built for anything connected to the Internet.'
    url: 'https://2c53ce48eb97cb20.xinnew.top/'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: f75556b255907b25
    name: f75556b255907b25
    url: 'https://f75556b255907b25.xinnew.top/'
    method: GET
    expectStatus: 200


